# CMake generated Testfile for 
# Source directory: /home/runner/work/ova-lib/ova-lib
# Build directory: /home/runner/work/ova-lib/ova-lib/_codeql_build_dir
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_queue "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_queue")
set_tests_properties(test_queue PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_priority_queue "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_priority_queue")
set_tests_properties(test_priority_queue PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_binary_heap "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_binary_heap")
set_tests_properties(test_binary_heap PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_fibonacci_heap "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_fibonacci_heap")
set_tests_properties(test_fibonacci_heap PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_hash "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_hash")
set_tests_properties(test_hash PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_array_list "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_array_list")
set_tests_properties(test_array_list PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_linked_list "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_linked_list")
set_tests_properties(test_linked_list PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_sorted_list "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_sorted_list")
set_tests_properties(test_sorted_list PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_sorter "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_sorter")
set_tests_properties(test_sorter PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_linked_stack "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_linked_stack")
set_tests_properties(test_linked_stack PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_array_stack "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_array_stack")
set_tests_properties(test_array_stack PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_matrix "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_matrix")
set_tests_properties(test_matrix PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_matrix_extra "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_matrix_extra")
set_tests_properties(test_matrix_extra PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_solver "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_solver")
set_tests_properties(test_solver PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_graph "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_graph")
set_tests_properties(test_graph PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_graph_algorithms "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_graph_algorithms")
set_tests_properties(test_graph_algorithms PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_avl_tree "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_avl_tree")
set_tests_properties(test_avl_tree PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_red_black_tree "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_red_black_tree")
set_tests_properties(test_red_black_tree PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_set "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_set")
set_tests_properties(test_set PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_trie "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_trie")
set_tests_properties(test_trie PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
add_test(test_bloom_filter "/home/runner/work/ova-lib/ova-lib/_codeql_build_dir/bin/test_bloom_filter")
set_tests_properties(test_bloom_filter PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;153;add_test;/home/runner/work/ova-lib/ova-lib/CMakeLists.txt;0;")
